version: '3.1'
services:
  stats-server:
    build: stats-server
    image: medi_stats_image
    container_name: medi_stats_container
    ports:
      - "9090:9090"
    depends_on:
      - medi-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://medi-stats-db:5432/medistats
      - DB_NAME=medistats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - DB_HOST=medi-stats-db
      - DB_PORT=6542

  medi-stats-db:
    image: postgres:14-alpine
    container_name: medi_stats_bd_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=medistats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=iamroot

  medi-main-service:
    build: medi-main-service
    image: medi_main_service_image
    container_name: medi_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - medi-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://medi-db:5432/medi
      - DB_NAME=medi
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=iamroot
      - DB_HOST=medi-db
      - DB_PORT=6541

  medi-db:
    image: postgres:14-alpine
    container_name: medi_bd_container
    ports:
        - "6541:5432"
    environment:
        - POSTGRES_DB=medi
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=iamroot
